
boost_vector: boost_vector.cpp
	g++ -o boost_vector boost_vector.cpp -I/sw/include/

static_class_var: static_class_var.cpp
	g++ -o static_class_var static_class_var.cpp

static_class_inhert_var: static_class_inhert_var.cpp
	g++ -o static_class_inhert_var static_class_inhert_var.cpp

file_read_time_test: file_read_time_test.cpp
	g++ -o file_read_time_test \
		-I$(HOME)/src/utils/c/timer/ \
		file_read_time_test.cpp \
		$(HOME)/src/utils/c/timer/timer.c 
